### ISSUE TITLE
Cannot compile (macOS Big Sur)

### ISSUE THREAD

**Issue by hey-stefan** [backslash-f/ShockEmu#6]
`stefan@Stefans-MacBook-Pro ShockEmu % ./build.sh only_keyboard.se
  File "shockemu.py", line 49
    print('{v} = {k};'.format(v=v,k=k),file=fp)
                                           ^
SyntaxError: invalid syntax
iohid_wrap.m:246:10: fatal error: 'mapKeys.h' file not found
#include "mapKeys.h"
         ^~~~~~~~~~~
1 error generated.`

**Comment by backslash-f** [comment]
I can't reproduce this one. I'm also on macOS BigSur.

It looks like you are missing the OSX Command Line Tools.

Please install it and try again: https://download.developer.apple.com/Developer_Tools/Command_Line_Tools_for_Xcode_12.4/Command_Line_Tools_for_Xcode_12.4.dmg
